"""add prompts

Revision ID: 0664f6a86de5
Revises: 68dc4b13f82c
Create Date: 2025-08-18 13:43:59.097090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0664f6a86de5'
down_revision: Union[str, Sequence[str], None] = '68dc4b13f82c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prompts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('prompt', sa.String(length=1000), nullable=False),
    sa.Column('response', sa.String(length=1000), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prompts_id'), 'prompts', ['id'], unique=False)
    op.create_index(op.f('ix_prompts_prompt'), 'prompts', ['prompt'], unique=True)
    op.create_index(op.f('ix_prompts_response'), 'prompts', ['response'], unique=True)
    op.create_index(op.f('ix_prompts_user_id'), 'prompts', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prompts_user_id'), table_name='prompts')
    op.drop_index(op.f('ix_prompts_response'), table_name='prompts')
    op.drop_index(op.f('ix_prompts_prompt'), table_name='prompts')
    op.drop_index(op.f('ix_prompts_id'), table_name='prompts')
    op.drop_table('prompts')
    # ### end Alembic commands ###
