"""update prompts table structure

Revision ID: f01df078b0f0
Revises: 0664f6a86de5
Create Date: 2025-08-18 13:55:11.416961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f01df078b0f0'
down_revision: Union[str, Sequence[str], None] = '0664f6a86de5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prompts', sa.Column('provider', sa.String(length=50), nullable=False))
    op.add_column('prompts', sa.Column('created_at', sa.DateTime(), nullable=True))
    # Convert user_id from VARCHAR to INTEGER, handling non-numeric values
    # First, update any non-numeric user_id values to NULL
    op.execute("UPDATE prompts SET user_id = NULL WHERE user_id !~ '^[0-9]+$'")
    # Then convert the column type
    op.execute("ALTER TABLE prompts ALTER COLUMN user_id TYPE INTEGER USING CASE WHEN user_id ~ '^[0-9]+$' THEN user_id::integer ELSE NULL END")
    op.alter_column('prompts', 'prompt',
               existing_type=sa.VARCHAR(length=1000),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('prompts', 'response',
               existing_type=sa.VARCHAR(length=1000),
               type_=sa.Text(),
               existing_nullable=False)
    op.drop_index(op.f('ix_prompts_prompt'), table_name='prompts')
    op.create_index(op.f('ix_prompts_prompt'), 'prompts', ['prompt'], unique=False)
    op.drop_index(op.f('ix_prompts_response'), table_name='prompts')
    op.create_index(op.f('ix_prompts_response'), 'prompts', ['response'], unique=False)
    op.drop_index(op.f('ix_prompts_user_id'), table_name='prompts')
    op.create_index(op.f('ix_prompts_user_id'), 'prompts', ['user_id'], unique=False)
    op.create_foreign_key(None, 'prompts', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'prompts', type_='foreignkey')
    op.drop_index(op.f('ix_prompts_user_id'), table_name='prompts')
    op.create_index(op.f('ix_prompts_user_id'), 'prompts', ['user_id'], unique=True)
    op.drop_index(op.f('ix_prompts_response'), table_name='prompts')
    op.create_index(op.f('ix_prompts_response'), 'prompts', ['response'], unique=True)
    op.drop_index(op.f('ix_prompts_prompt'), table_name='prompts')
    op.create_index(op.f('ix_prompts_prompt'), 'prompts', ['prompt'], unique=True)
    op.alter_column('prompts', 'response',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=1000),
               existing_nullable=False)
    op.alter_column('prompts', 'prompt',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=1000),
               existing_nullable=False)
    op.alter_column('prompts', 'user_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=50),
               nullable=False)
    op.drop_column('prompts', 'created_at')
    op.drop_column('prompts', 'provider')
    # ### end Alembic commands ###
